services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: telas
      POSTGRES_PASSWORD: telas123
      POSTGRES_DB: telas_app
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telas -d telas_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
